serviceTree:
  landscape: lapras
  platform: dn___platform___
  service: dn___service___
  module: migration

aspNetEnv: Development

backoffLimit: 4
ttlSecondsAfterFinished: 60
appSettings:
  App:
    Mode: Migration

annotations: {}

envFromSecret: dn___platform___-dn___service___

configMountPath: /app/App/Config/settings.yaml

image:
  repository: dotnet-migration
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ''

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

serviceAccount:
  create: false
  annotations: {}
  name: ''

podAnnotations: {}

podSecurityContext: {}

securityContext: {}
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: 'topology.kubernetes.io/zone'
    whenUnsatisfiable: ScheduleAnyway
    matchLabels:
      atomi.cloud/landscape: lapras
      atomi.cloud/platform: dn___platform___
      atomi.cloud/service: dn___service___
      atomi.cloud/module: migration
