#
name: CD

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  #
  docker:
    name: Build Docker Image
    uses: ./.github/workflows/⚡reusable-docker.yaml
    secrets: inherit
    with:
      atomi_platform: dn___platform___
      atomi_service: dn___service___

      dockerfile: ./infra/Dockerfile
      image_name: api

      version: ${{ github.ref_name }}
  #
  #
  helm:
    name: Helm Chart
    uses: ./.github/workflows/⚡reusable-helm.yaml
    secrets: inherit
    with:
      atomi_platform: dn___platform___
      atomi_service: dn___service___
      chart_path: ./infra/root_chart

      version: ${{ github.ref_name }}
  #
#
