name: CI

on:
  push:

jobs:
  precommit:
    name: Pre-Commit
    uses: ./.github/workflows/⚡reusable-precommit.yaml
    secrets: inherit
    with:
      atomi_platform: dn___platform___
      atomi_service: dn___service___
  #
  docker:
    name: Build Docker
    uses: ./.github/workflows/⚡reusable-docker.yaml
    secrets: inherit
    with:
      atomi_platform: dn___platform___
      atomi_service: dn___service___

      dockerfile: ./infra/Dockerfile
      image_name: api
  #
  #
  helm:
    name: Helm Chart
    uses: ./.github/workflows/⚡reusable-helm.yaml
    secrets: inherit
    with:
      atomi_platform: dn___platform___
      atomi_service: dn___service___
      chart_path: ./infra/root_chart
  #
