name: CI

on:
  push:

jobs:
  precommit:
    name: Pre-Commit
    uses: ./.github/workflows/⚡reusable-precommit.yaml
    secrets: inherit
    with:
      atomi_platform: dn___platform___
      atomi_service: dn___service___
  build-api:
    name: Build API Image
    uses: ./.github/workflows/⚡reusable-docker.yaml
    secrets: inherit
    with:
      atomi_platform: dn___platform___
      atomi_service: dn___service___

      dockerfile: ./infra/Dockerfile
      image_name: api
  build-migrate:
    name: Build Migration Image
    uses: ./.github/workflows/⚡reusable-docker.yaml
    secrets: inherit
    with:
      atomi_platform: dn___platform___
      atomi_service: dn___service___

      dockerfile: ./infra/migrate.Dockerfile
      image_name: migrate
  helm:
    name: Helm Chart
    uses: ./.github/workflows/⚡reusable-helm.yaml
    secrets: inherit
    with:
      atomi_platform: dn___platform___
      atomi_service: dn___service___
      chart_path: ./infra/root_chart
