$schema: ./schema.json

# Native
AllowedHosts: '*'
Kestrel:
  Endpoints:
    Http:
      Url: http://+:9003
Logging:
  LogLevel:
    Default: Information
  #  Console:
  #    LogLevel:
  #      Default: Debug
  OpenTelemetry:
    IncludeFormattedMessage: true
    IncludeScopes: true
    ParseStateValues: false
# Domain
App:
  Landscape: lapras
  Platform: alcohol
  Service: zinc
  Module: api
  Mode: Server
  DefaultCors: AllowAll
  Version: 1.0.0
  EnableSwagger: true
  GenerateConfig: false
Swagger:
  Title: Lapras Alcohol Zinc API
  Description: 'Alcohol-Zinc: API for Phinish'
  OpenApiContact:
    Name: kirinnee
    Email: kirinnee97@gmail.com
ErrorPortal:
  Enabled: true
  Scheme: http
  Host: localhost:3000
  EnableExceptionResponse: true
# Security
Cors:
  - Name: AllowAll
    PreflightMaxAge: 600

# OTEL
Logs:
  Exporter:
    Console:
      Enabled: false
    Otlp:
      Enabled: false
      Endpoint: 'http://silicon-otlp-collector.sulfoxide.svc:4317'
      ProcessorType: Batch # or simple
      Protocol: Grpc # or HttpProtobuf
      Timeout: 30000
      BatchSize: 512
      QueueSize: 2048
      Delay: 5000
      Headers: ''

Trace:
  Instrument:
    EFCore:
      Enabled: true
      SetDbStatementForStoredProcedure: true
      SetDbStatementForText: true
    AspNetCore:
      Enabled: true
      GrpcSupport: true
      RecordException: true
    HttpClient:
      Enabled: true
      RecordException: true
    SqlClient:
      Enabled: false
      RecordException: true
      SetDbStatementForStoredProcedure: true
      EnableConnectionLevelAttributes: true
      SetDbStatementForText: true
    GrpcClient:
      Enabled: true
      SuppressDownstreamInstrumentation: true
  Exporter:
    Console:
      Enabled: false
    Otlp:
      Enabled: false
      Endpoint: 'http://silicon-otlp-collector.sulfoxide.svc:4317'
      Timeout: 30000
      ProcessorType: Batch # or simple
      Protocol: Grpc # or HttpProtobuf
      BatchSize: 512
      QueueSize: 2048
      Delay: 5000
      Headers: ''

Metrics:
  Instrument:
    AspNetCore: true
    HttpClient: true
    Process: true
    Runtime: true
  Exporter:
    Console:
      Enabled: false
      ExportInterval: 1000
    Otlp:
      Enabled: false
      Endpoint: 'http://silicon-otlp-collector.sulfoxide.svc:4317'
      ExportInterval: 1000
      Timeout: 30000
      ProcessorType: Batch # or simple
      Protocol: Grpc # or HttpProtobuf
      BatchSize: 512
      QueueSize: 2048
      Delay: 5000
      Headers: ''

# Infra-based
Database:
  MAIN:
    Host: zinc-maindb
    User: admin
    Password: supersecret
    AutoMigrate: false
    Database: alcohol-zinc
    Port: 5432
    Timeout: 60
Cache:
  MAIN:
    Endpoints:
      - zinc-maincache:6379
    Password: supersecret

    ConnectTimeout: 5000
    AbortConnect: true
    AllowAdmin: false
    ConnectRetry: 3
    SSL: false
    SyncTimeout: 5000
BlockStorage:
  MAIN:
    AccessKey: 'admin'
    SecretKey: 'supersecret'
    Bucket: 'alcohol-zinc-main-storage'
    Read:
      Host: mainstorage.zinc.alcohol.lapras.lvh.me
      Port: 443
      Scheme: https
    Write:
      Host: zinc-mainstorage
      Port: 443
      Scheme: https
    Policy: Private
    UseSSL: true
    EnsureBucketCreation: false
Smtp:
  TRANSACTIONAL:
    Host: email-smtp.ap-southeast-1.amazonaws.com
    Port: 2587
    Username: transactional-user
    Password: transactional-secret
    FromEmail: noreply@notifications.lazytax.club
    FromName: LazyTax Notifications
    EnableSsl: true
    UseDefaultCredentials: false
    Timeout: 5000
# external
HttpClient:
  Logto:
    BaseAddress: https://xzc47u.logto.app
    Timeout: 60
Auth:
  Enabled: true
  Management:
    Endpoint: https://xzc47u.logto.app
    Id: r0lqrwbrp3ao2d5wb8pv9
    Secret: supersecret
    Resource: https://xzc47u.logto.app/api
    Scope: all
  Settings:
    Policies:
      OnlyAdmin:
        Target:
          - admin
        Type: 'All'
        Field: 'scope'
      Registered:
        Target:
          - 'true'
        Type: 'All'
        Field: 'alcohol_zinc'
    Issuer: https://xzc47u.logto.app/oidc
    Audience: https://api.zinc.alcohol.lapras
    Domain: xzc47u.logto.app/oidc
    TokenValidation:
      ValidateAudience: true
      ValidateIssuer: true
      ClockSkew: 0
      ValidateLifetime: true
      ValidateIssuerSigningKey: true
