apiVersion: v2
name: root-chart
description: Root Chart for dn___platform___ dn___service___

type: application
version: 0.1.0
appVersion: '1.16.0'

dependencies:
  # Root Chart
  - name: dotnet-chart
    version: 0.1.0
    repository: file://../api_chart
    condition: api.enabled
    alias: api
  # Migration
  - name: dotnet-migration
    version: 0.1.0
    repository: file://../migration_chart
    condition: migration.enabled
    alias: migration

  # Secrets
  - name: sulfoxide-bromine
    version: 1.8.0
    condition: bromine.enable
    alias: bromine
    repository: oci://ghcr.io/atomicloud/sulfoxide.bromine

  # Databases
  - name: postgresql
    version: 15.5.16
    repository: oci://registry-1.docker.io/bitnamicharts
    alias: maindb
    condition: maindb.enable

  # Blob Storage
  - name: minio
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 14.6.20
    alias: mainstorage
    condition: mainstorage.enable

  # Caches
  - name: dragonfly
    repository: oci://ghcr.io/dragonflydb/dragonfly/helm
    version: v1.20.1
    alias: maincache
    condition: maincache.enable
