serviceTree:
  landscape: &landscape pikachu

bromine:
  enable: true
  target: &target dn___service___
  serviceTree:
    landscape: *landscape

# -- YAML Anchor for PodSecurityContext
podSecurityContext: &podSecurityContext
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true

# -- YAML Anchor for SecurityContext
securityContext: &securityContext
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  capabilities:
    drop:
      - ALL
xSecurityContext: &migrateSecurityContext
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  capabilities:
    drop:
      - ALL
api:
  enabled: true
  fullnameOverride: 'dn___service___-api'
  envFromSecret: *target
  serviceTree:
    landscape: *landscape
  image:
    repository: ghcr.io/atomicloud/dn___platform___.dn___service___/api
  imagePullSecrets: []
  securityContext: *securityContext
  podSecurityContext: *podSecurityContext
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  configMountPath: /app/Config

  service:
    type: ClusterIP
    port: 80
    containerPort: 9050

  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: 'entei-dn___service___-letsencrypt-issuer'
    hosts:
      - host: api.dn___service___.dn___platform___.pikachu.cluster.atomi.cloud
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - api.dn___service___.dn___platform___.pikachu.cluster.atomi.cloud
        secretName: api-dn___service___-dn___platform___-pikachu-tls

migration:
  enabled: true
  fullnameOverride: 'dn___service___-migration'
  envFromSecret: *target
  securityContext: *migrateSecurityContext
  podSecurityContext: *podSecurityContext
  configMountPath: /app/Config

  image:
    repository: ghcr.io/atomicloud/dn___platform___.dn___service___/migrate
  serviceTree:
    landscape: *landscape

maindb:
  enable: false

maincache:
  enable: false

mainstorage:
  enable: false
