serviceTree:
  landscape: &landscape lapras

bromine:
  enable: true
  serviceTree:
    landscape: *landscape

api:
  enabled: true
  serviceTree:
    landscape: *landscape

  fullnameOverride: 'dn___service___-api'
  replicaCount: 1

  configMountPath: /app/App/Config

  service:
    type: ClusterIP
    port: 80
    containerPort: 9001

  ingress:
    enabled: true
    className: traefik
    hosts:
      - host: api.dn___service___.dn___platform___.lapras.lvh.me
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

migration:
  fullnameOverride: 'dn___service___-migration'
  enabled: false

maindb:
  enable: true
  fullnameOverride: 'dn___service___-maindb'

maincache:
  enable: true
  fullnameOverride: 'dn___service___-maincache'
  resources:
    requests:
      memory: '256Mi'
      cpu: '100m'
    limits:
      memory: '512Mi'
      cpu: '250m'

mainstorage:
  enable: true
  fullnameOverride: 'dn___service___-mainstorage'
